name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'brigandyne.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - uses: actions/upload-artifact@v1
        with:
          name: brigandyne.zip
          path: ${{ github.workspace }}/result.zip
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
      with:
      files: lang/ styles/ system.json
      dest: release.zip
      - uses: actions/upload-artifact@v1
        with:
          name: brigandyne
          path: ${{ github.workspace }}/brigandyne.zip