name: Create Archive
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'brigandyne.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Upload Archive
        uses: actions/upload-artifact@v1
        with:
          artifacts: 'brigandyne.zip'
          path: ${{ github.workspace }}/brigandyne.zip
